defaults: &defaults
  to_label_methods: [name, title]
  image_mime_types: [image/jpg, image/jpeg, image/png, image/gif]
  help:
    title: false
  export:
    default_col_sep: ";"
  filters:
    model_name: null  # for enabling saved filter set to 'Filter' model for instance
  import:
    mime_types: [text/csv, text/plain]
    model_name: Import
    default_action: :import
    association_name: :imports # null to disable
    association_name_join_table: :imports_importables
    state_types:
    - - Čeká na konfiguraci
      - not_configured
    - - Čeká na spuštění
      - not_started
    - - Zpracovává se
      - processing
    - - Dokončeno
      - finished

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
